title: Ian Steffensen # your name (or website title) here
logo: IMG_0649 (1).jpg # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Driven Finance Analyst <br>
  Soccer Fanatic  <br><br>
  <a href="https://www.linkedin.com/in/averyjsmith/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
